(() => {
'use strict';
const C=window.PANDAS_CONFIG,D=window.PandasData,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>D.str(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=v=>{try{const u=new URL(D.str(v));return /^https?:$/.test(u.protocol)?u.href:'';}catch{return '';}};
const imageUrl=v=>url(v)||(/^images\/[\w .%()-]+\.(png|jpe?g|webp|gif|avif|svg)$/i.test(D.str(v))&&!D.str(v).includes('..')?D.str(v):'');
const external=(href,label,cls='')=>url(href)?`<a class="${cls}" href="${esc(url(href))}" target="_blank" rel="noopener noreferrer">${label}<span class="sr-only"> (opens in new tab)</span></a>`:'';
let state=null,selected='',view='upcoming',limit=12,busy=false,currentEvents=[],lastRaw=null,loadedAt=0,lastSource='live';
const cacheKey='pandas:v1:'+C.sheetId;
const preview=new URLSearchParams(location.search).has('preview');
let paused=false;try{paused=localStorage.getItem('pandas:motion')==='paused';}catch{}
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function setMotion(value){paused=value;document.documentElement.classList.toggle('no-motion',paused);const b=$('.motion-toggle');b.setAttribute('aria-pressed',String(paused));b.setAttribute('aria-label',paused?'Enable motion':'Pause motion');b.title=paused?'Enable motion':'Pause motion';b.innerHTML=`<span aria-hidden="true">${paused?'▷':'Ⅱ'}</span>`;}
setMotion(paused||reduced);
$('.motion-toggle').addEventListener('click',()=>{setMotion(!paused);try{localStorage.setItem('pandas:motion',paused?'paused':'enabled');}catch{}});
const name=()=>D.str(state?.settings['Team name'])||C.defaultName;
const teamMatch=r=>!selected||!D.str(r.Team)||D.str(r.Team)===selected;
const events=()=>state.schedule.filter(teamMatch);
const prettyDate=(date,options={month:'short',day:'numeric'})=>new Intl.DateTimeFormat('en-US',{...options,timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'));
const prettyTime=t=>{if(!t)return 'Time TBD';const [h,m]=t.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`;};
const title=e=>e.Type==='Game'?`${e['Home / Away']==='Away'?'at':'vs'} ${D.str(e['Opponent / Title'])}`:D.str(e['Opponent / Title']);
const gcFor=e=>url(e['GameChanger URL'])||url(state.teams.find(t=>t.Team===e.Team)?.['GameChanger URL'])||(!e.Team&&state.teams.length===1?url(state.teams[0]['GameChanger URL']):'');
function statusText(e){if(e.Status==='Scheduled'&&!D.upcoming(e))return e.Type==='Game'?'Awaiting result':'Past';return e.Status;}
function actions(e,calendar=true){const location=D.str(e.Address)||D.str(e.Location);return `<div class="event-actions">${location?external('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(location),'Directions ↗'):''}${calendar&&!['Canceled','Postponed','Final'].includes(e.Status)?`<button data-calendar="${e._id}" aria-label="Add ${esc(title(e))} to calendar">Calendar +</button>`:''}${external(gcFor(e),'GameChanger ↗')}</div>`;}
function showSection(id,on){$('#'+id).hidden=!on;const n=$(`[data-nav="${id}"]`);if(n)n.hidden=!on;}
function setText(selector,text){const el=$(selector);el.textContent=text;el.hidden=!text;}
function renderBrand(){const s=state.settings,n=name();document.title=n;$$('[data-brand]').forEach(e=>e.textContent=n.toUpperCase());$('#hero-bottom-name').textContent=n.toUpperCase();$('.art-caption').textContent=n.toUpperCase();const words=n.trim().split(/\s+/),breakAt=Math.max(1,Math.floor(words.length/2));$('#hero-title').innerHTML=words.length>1?`<span>${esc(words.slice(0,breakAt).join(' '))}</span><span>${esc(words.slice(breakAt).join(' '))}<span class="period">.</span></span>`:`<span>${esc(n)}<span class="period">.</span></span>`;setText('#sport',D.str(s.Sport));setText('#season',D.str(s.Season));setText('#subtitle',D.str(s.Subtitle));const logo=imageUrl(s['Logo URL'])||C.defaultLogo;for(const el of [$('#hero-logo'),$('.brand-icon img')]){if(el.getAttribute('src')!==logo)el.src=logo;}
 const email=D.str(s['Contact email']);const validEmail=/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(email);$('#contact').hidden=!validEmail;if(validEmail)$('#contact').href='mailto:'+email;setText('#footer-note',D.str(s['Footer note']));$('#copyright').textContent=`© ${new Date().getFullYear()} ${n}`;
 const teams=state.teams;$('#team-control').hidden=teams.length<2;if(selected&&!teams.some(t=>t.Team===selected))selected='';$('#team-select').innerHTML='<option value="">All teams</option>'+teams.map(t=>`<option value="${esc(t.Team)}">${esc(t.Team)}${t.Label?' · '+esc(t.Label):''}</option>`).join('');$('#team-select').value=selected;
 const gc=teams.filter(teamMatch).filter(t=>url(t['GameChanger URL']));const button=$('#hero-gc');button.hidden=gc.length===0;if(gc.length===1){button.href=url(gc[0]['GameChanger URL']);button.target='_blank';button.rel='noopener noreferrer';}else if(gc.length>1){button.href='#links';button.removeAttribute('target');button.removeAttribute('rel');}
}
function renderNext(){const next=events().find(e=>D.upcoming(e)&&!['Canceled','Postponed','Final'].includes(e.Status));$('.next-label').innerHTML=`<span class="status-dot ${next?.Status==='Live'?'live':''}"></span>${next?.Status==='Live'?'LIVE NOW':'UP NEXT'}`;
 $('#next-event').innerHTML=next?`<p class="eyebrow">${esc(next.Type)}${next.Team?' / '+esc(next.Team):''}</p><h2>${esc(title(next))}</h2><p>${esc(prettyDate(next._date,{weekday:'short',month:'short',day:'numeric',year:'numeric'}))} · ${esc(prettyTime(next._time))}${next.Location?' · '+esc(next.Location):''}</p>${actions(next)}`:`<h2>No upcoming events</h2><p>The next event will appear here when posted.</p>`;
 const r=D.record(events()),total=r.wins+r.losses+r.ties;$('#record').hidden=!total||!D.yes(state.settings['Show record']);$('#record').innerHTML=`<div class="record"><div><strong>${r.wins}</strong><small>WINS</small></div><div><strong>${r.losses}</strong><small>LOSSES</small></div><div><strong>${r.ties}</strong><small>TIES</small></div></div><p class="record-caption">${esc(selected||'SEASON RECORD')}</p>`;
}
function renderSchedule(){const type=$('#event-type').value;const list=events().filter(e=>(!type||e.Type===type)&&(view==='all'||(view==='upcoming'?D.upcoming(e):!D.upcoming(e))));if(view==='results')list.reverse();currentEvents=list;
 $$('#schedule [data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));
 $('#schedule-list').innerHTML=list.length?list.slice(0,limit).map(e=>{
  const score=D.scores(e),status=statusText(e);return `<article class="event-row"><div class="date-block"><span class="month">${esc(prettyDate(e._date,{month:'short'}).toUpperCase())}</span><span class="day">${+e._date.slice(8)}</span><span class="weekday">${esc(prettyDate(e._date,{weekday:'short'}).toUpperCase())}</span></div><div><div class="event-meta"><span class="badge ${esc(e.Status.toLowerCase())}">${esc(status)}</span><span>${esc(e.Type)}${e.Team?' / '+esc(e.Team):''}</span></div><h3 class="event-title">${esc(title(e))}</h3>${e.Notes?`<p class="event-note">${esc(e.Notes)}</p>`:''}</div><div class="event-location"><strong>${esc(prettyTime(e._time))}</strong>${esc(e.Location||'Location TBD')}<div class="small">${esc(prettyDate(e._date,{year:'numeric'}))}${e['Home / Away']?' · '+esc(e['Home / Away']):''}</div></div>${score?`<div class="score">${score[0]} <span class="muted">–</span> ${score[1]}<small>${score[0]>score[1]?'WIN':score[0]<score[1]?'LOSS':'TIE'}</small></div>`:actions(e)}</article>`;
 }).join(''):`<div class="empty"><strong>${view==='results'?'No results yet':view==='upcoming'?'Schedule coming soon':'No events posted'}</strong>${type?'No '+esc(type.toLowerCase())+' events match this view.':'Check back for team events.'}</div>`;
 $('#show-more').hidden=list.length<=limit;$('#show-more').textContent=`Show more events (${Math.max(0,list.length-limit)} remaining)`;$('#calendar-download').hidden=!list.some(e=>!['Canceled','Postponed','Final'].includes(e.Status)&&D.upcoming(e));
}
function renderAnnouncements(){const list=state.announcements.filter(teamMatch).filter(a=>D.activeAnnouncement(a));const rank={Urgent:0,Pinned:1,Normal:2};list.sort((a,b)=>(rank[a.Priority]??2)-(rank[b.Priority]??2)||D.str(b['Start date']).localeCompare(D.str(a['Start date'])));showSection('updates',list.length>0);$('#announcements').innerHTML=list.map(a=>`<article class="announcement ${esc(D.str(a.Priority).toLowerCase())}"><span class="${a.Priority==='Urgent'||a.Priority==='Pinned'?'badge '+a.Priority.toLowerCase():'announcement-date'}">${esc(a.Priority==='Urgent'?'IMPORTANT':a.Priority==='Pinned'?'PINNED':D.cleanDate(a['Start date'])?prettyDate(D.cleanDate(a['Start date'])):'TEAM UPDATE')}${a.Team?' / '+esc(a.Team):''}</span><h3>${esc(a.Title)}</h3><p>${esc(a.Message)}</p>${external(a['Link URL'],esc(a['Link label']||'Details')+' ↗')}</article>`).join('');}
function renderRoster(){const list=state.roster.filter(teamMatch);showSection('roster',D.yes(state.settings['Show roster'])&&list.length>0);const q=$('#roster-search').value.toLowerCase().trim();const filtered=list.filter(p=>[p.Name,p.Number,p.Position,p.Role].some(v=>D.str(v).toLowerCase().includes(q)));$('#roster-grid').innerHTML=filtered.length?filtered.map(p=>`<article class="player ${p.Role==='Coach'?'coach':''}">${imageUrl(p['Photo URL'])?`<img src="${esc(imageUrl(p['Photo URL']))}" alt="" loading="lazy">`:''}<span class="player-number">${esc(p.Role==='Coach'?'C':D.str(p.Number)||'—')}</span><div><h3>${esc(p.Name)}</h3><p>${esc([p.Role==='Coach'?'Coach':p.Position,p.Team&&state.teams.length>1?p.Team:''].filter(Boolean).join(' · '))}</p></div></article>`).join(''):'<p class="empty">No matching players or coaches.</p>';}
function renderLinks(){const gc=state.teams.filter(teamMatch).filter(t=>url(t['GameChanger URL'])).map(t=>({Label:t.Team,URL:t['GameChanger URL'],Category:'GameChanger'}));const list=[...gc,...state.links.filter(teamMatch).filter(l=>url(l.URL))];showSection('links',list.length>0);$('#links-grid').innerHTML=list.map(l=>external(l.URL,`<span><small>${esc(l.Category||'Team link')}</small><span class="label">${esc(l.Label)}</span></span><span class="link-arrow" aria-hidden="true">↗</span>`,'link-card'+(l.Category==='GameChanger'?' gc':''))).join('');}
function renderGallery(){const list=state.gallery.filter(teamMatch).filter(p=>imageUrl(p['Image URL']));showSection('gallery',D.yes(state.settings['Show gallery'])&&list.length>0);$('#gallery-grid').innerHTML=list.map(p=>`<button class="photo" data-photo="${esc(imageUrl(p['Image URL']))}" data-caption="${esc(p.Caption)}" aria-label="Open photo${p.Caption?': '+esc(p.Caption):''}"><img src="${esc(imageUrl(p['Image URL']))}" alt="${esc(p.Caption||'Team photo')}" loading="lazy">${p.Caption?`<span>${esc(p.Caption)}</span>`:''}</button>`).join('');}
function renderSponsors(){showSection('sponsors',state.sponsors.length>0);$('#sponsors-grid').innerHTML=state.sponsors.map(s=>{const body=`${imageUrl(s['Logo URL'])?`<img src="${esc(imageUrl(s['Logo URL']))}" alt="" loading="lazy">`:''}<span>${esc(s.Name)}</span>`;return url(s['Website URL'])?external(s['Website URL'],body,'sponsor'):`<div class="sponsor">${body}</div>`;}).join('');}
function render(){renderBrand();renderNext();renderAnnouncements();renderSchedule();renderRoster();renderLinks();renderGallery();renderSponsors();}
function saveCache(raw){try{localStorage.setItem(cacheKey,JSON.stringify({timestamp:Date.now(),raw}));}catch{}}
function readCache(){try{const c=JSON.parse(localStorage.getItem(cacheKey));return c&&Date.now()-c.timestamp<C.cacheHours*3600000?c:null;}catch{return null;}}
function syncText(text){$('#sync-status').textContent=text;}
function freshness(){if(!loadedAt)return '';return new Intl.DateTimeFormat('en-US',{timeZone:C.timezone,month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(loadedAt))+' CT';}
async function refresh(){if(busy||preview)return;busy=true;$('#refresh').disabled=true;syncText('Updating team information…');try{const raw=await D.load();loadedAt=Date.now();lastSource='live';if(JSON.stringify(raw)!==JSON.stringify(lastRaw)){state=D.model(raw);lastRaw=raw;render();}saveCache(raw);syncText('Updated '+freshness());}catch(error){if(!state){const cache=readCache();if(cache){lastRaw=cache.raw;state=D.model(cache.raw);loadedAt=cache.timestamp;lastSource='cached';render();}else{$('#next-event').innerHTML='<h2>Team updates unavailable</h2><p>Check your connection and try Refresh.</p>';$('#schedule-list').innerHTML='<div class="empty"><strong>Unable to load the schedule</strong>Please try again shortly.</div>';$('#calendar-download').hidden=true;}}syncText(state?'Connection unavailable · Showing saved info from '+freshness():'Could not load team information. Try Refresh.');}finally{busy=false;$('#refresh').disabled=false;}}
function download(eventsToSave){if(!eventsToSave.length)return;const blob=new Blob([D.ics(eventsToSave,selected||name())],{type:'text/calendar;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='trash-pandas-schedule.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('#team-select').addEventListener('change',e=>{selected=e.target.value;limit=12;render();});
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;limit=12;if(state)renderSchedule();}));
$('#event-type').addEventListener('change',()=>{limit=12;if(state)renderSchedule();});$('#roster-search').addEventListener('input',()=>state&&renderRoster());$('#show-more').addEventListener('click',()=>{limit+=12;renderSchedule();});$('#refresh').addEventListener('click',refresh);
$('#calendar-download').addEventListener('click',()=>download(currentEvents.filter(e=>D.upcoming(e)&&!['Canceled','Postponed','Final'].includes(e.Status))));
const dialog=$('#photo-dialog');document.addEventListener('click',e=>{const calendar=e.target.closest('[data-calendar]');if(calendar&&state){const event=state.schedule.find(x=>x._id===Number(calendar.dataset.calendar));if(event)download([event]);}const photo=e.target.closest('[data-photo]');if(photo){$('#dialog-image').src=photo.dataset.photo;$('#dialog-image').alt=photo.dataset.caption||'Team photo';$('#dialog-caption').textContent=photo.dataset.caption;dialog.showModal();}});
$('.photo-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
// Broken remote images never remove a player's name or the team's identity.
document.addEventListener('error',e=>{if(e.target.tagName!=='IMG')return;const img=e.target;if((img.id==='hero-logo'||img.closest('.brand-icon'))&&!img.src.endsWith(C.defaultLogo)){img.src=C.defaultLogo;}else if(!img.closest('.hero-art')&&!img.closest('.brand-icon'))img.hidden=true;},true);
window.addEventListener('online',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()-loadedAt>C.refreshMs)refresh();});
setInterval(()=>{if(!document.hidden)refresh();},C.refreshMs);
setInterval(()=>{if(state&&!document.hidden){renderNext();renderAnnouncements();renderSchedule();}},60000);
function previewData(){const day=D.today(),future=D.addDays(day,3),past=D.addDays(day,-2);const team='Trash Pandas';return {Settings:[{Setting:'Team name',Value:team},{Setting:'Sport',Value:'Baseball'},{Setting:'Subtitle',Value:'Design preview'},{Setting:'Season',Value:'2027'},{Setting:'Show roster',Value:'Yes'},{Setting:'Show record',Value:'Yes'},{Setting:'Show gallery',Value:'Yes'}],Teams:[{Publish:true,Team:team,'GameChanger URL':'https://gc.com',Order:1}],Schedule:[{Publish:true,Team:team,Type:'Game',Date:future,Time:'18:30','Opponent / Title':'Visitors','Home / Away':'Home',Location:'Home field',Status:'Scheduled'},{Publish:true,Team:team,Type:'Practice',Date:D.addDays(day,1),Time:'17:30','Opponent / Title':'Team practice',Location:'Practice field',Status:'Scheduled',Notes:'Bring your gear and water.'},{Publish:true,Team:team,Type:'Game',Date:past,Time:'14:00','Opponent / Title':'Visitors','Home / Away':'Away',Location:'Away field',Status:'Final','Our score':8,'Their score':3}],Roster:Array.from({length:8},(_,i)=>({Publish:true,Team:team,Number:[2,7,11,14,21,24,30,42][i],Name:'Player '+(i+1),Role:'Player',Position:['Pitcher','Catcher','Infield','Outfield'][i%4]})),Announcements:[{Publish:true,Title:'Practice update',Message:'Check the schedule for our next team practice.',Priority:'Pinned'},{Publish:true,Title:'Follow the team',Message:'Find our GameChanger link below for game updates.',Priority:'Normal'}],Links:[{Publish:true,Label:'Team store',URL:'https://example.com',Category:'Store'}],Sponsors:[],Gallery:[]};}
if(preview){$('#preview-banner').hidden=false;$('#refresh').hidden=true;state=D.model(previewData());render();syncText('Preview · sample content');}else{refresh();}
})();
